name: Create Release PR

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release
          branch: main
          title: 'chore: sync main to release'
          body: |
            이 PR은 메인 브랜치의 변경사항을 릴리즈 브랜치로 동기화합니다.

            이 PR이 머지되면 릴리즈 워크플로우가 자동으로 트리거됩니다.
          # labels: |
          #   automated-pr
          #   sync-to-release
